services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 7007:7007
      - 9229:9229
    command: npm run start
    depends_on:
      - postgres
    restart: always

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIA_DB_PASSWORD}
      MYSQL_DATABASE: ${MARIA_DB_NAME}
      MYSQL_USER: ${MARIA_DB_USER}
      MYSQL_PASSWORD: ${MARIA_DB_PASSWORD}
    ports:
      - '${MARIA_DB_PORT}:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local
